import discord
from discord.ext import commands
from client_config import client, intents, SERVER_ID
import random

beer_trigger = [
    "piwo", "piwa", "piwu", "piwo", "piwem", "piwie", "piwach", "piwom",
    "piwko", "piwka", "piwku", "piwko", "piwkiem", "piwku", "piwkach", "piwkom",
    "piwerko", "piwerka", "piwerku", "piwerko", "piwerkiem", "piwerku", "piwerkach", "piwerkami",
    "browar", "browaru", "browarowi", "browar", "browarem", "browarze", "browary", "browarom"
]

beer_response = [
    "Piwo to moje paliwo!",
    "Piwko to moje paliwko!",
    "Piwo ucisza Iwo",
    "Czy ktoś powiedział Piwo?",
    "Mmm, piwo, moje ulubione",
    "Piwo? Jakie jest Twoje ulubione?",
    "Ouu Yeah!",
    "Stawiasz?",
    "To jest to!",
    "Jakieś flanki?",
    "Zeruje szybciej niż Ty",
    "Tankujemy?",
    "Ach ten Nektar Bogów",
    "Ekipa W4 lubi to.",
    "Puszka czy butelka?",
    "No i namówiłeś",
    "Ale bym się napił..",
    "Piwo? Nigdy się odmówię",
    "Które najbardziej lubisz?",
    "Wypijmy za to!",
    "Piwo zawsze na propsie",
    "Piwne piękności",
    "Piwo na każdą okazję",
    "Piwo, bo życie jest piękne",
    "Kufel w dłoń, świat do zdobycia",
    "Piwne mądrości",
    "Piwo poprawia humor",
    "Kto nie pije, ten nie żyje",
    "Na zdrowie i do dna!",
    "Piwo rozwiązuje problemy",
    "Piwo — to jest to, co kocham!",
    "W piwie prawda się kryje",
    "Dobre piwo, dobre życie",
    "Piwo, bo nikt nie jest doskonały",
    "Na chłodno, z kumplami",
    "Zawsze czas na piwko",
    "Piwo — antidotum na nudę",
    "Piana, zapach, smak - piwne doznania",
    "W piwie siła!",
    "Zawsze jest dobry czas na piwo",
    "Piwo - eliksir szczęścia",
    "Wszystko lepsze z piwem",
    "Piwne chwile są najlepsze",
    "Piwo i przyjaciele, doskonałe połączenie",
    "Na dnie każdego piwa jest uśmiech",
    "Pij odpowiedzialnie, ale pij!",
    "Piwo, bo zawsze W4RTO!",
    "Piwne czary",
    "Niech piwo płynie!",
    "Piwo to najlepsza nagroda",
    "Zimne piwo i ciepłe serce",
    "Wszystko lepsze z kuflem w ręce",
    "Piwny klimat",
    "Piwo, bo inaczej nie ma sensu",
    "Róbmy piwne plany",
    "Kufel zawsze pełny optymizmu",
    "Piwo na każdy dzień tygodnia",
    "Zawsze w dobrym piwnym towarzystwie",
    "Piwo - najlepsza forma relaksu",
    "Zimne piwo, gorące wspomnienia",
    "Piwo naładowuje baterie",
    "Nigdy nie odmawiam piwa",
    "Piwo i życie nabierają smaku",
    "Kto piwo pić nie umie, ten niech idzie się schować",
    "Piwo i do przodu!",
    "Kto nie pił, ten nie wie, co traci",
    "Piwo, bo za chwilę już weekend!",
    "Piwne spojrzenie na świat",
    "Piwne wspomnienia",
    "Niech piwo będzie zawsze na stole",
    "Piwo, bo życie jest za krótkie na tanie trunki",
    "W każdym piwie jest trochę magii",
    "Piwo dodaje skrzydeł",
    "Rozkoszuj się każdym łykiem piwa",
    "Piwo - najlepszy sposób na zrelaksowanie się",
    "Zawsze gotów na kufel",
    "Piwo, bo jutro może być za późno",
    "Wypiłem piwo, więc jestem",
    "Na piwo zawsze jest czas",
    "Piwo to nie tylko napój, to styl życia",
    "Niech piwo rozjaśnia każdy dzień",
    "Kufel w dłoni, uśmiech na twarzy",
    "Piwo - pomysł na udany wieczór",
    "Piwny raj na ziemi",
    "Kufel w ręce, a świat stoi otworem",
    "Piwo, bo piątek",
    "Niech piwo płynie jak rzeka",
    "Każde piwo ma swoją historię",
    "Zawsze miejsce na kolejne piwko",
    "Piwo, bo życie to nie tylko praca",
    "Piwne uniesienia",
    "Piwo - najlepszy kompan na wieczór",
    "Na piwo zawsze jest dobry moment",
    "Piwo, bo dzisiaj jest dzisiaj",
    "Kto nie pił piwa, niech pierwszy rzuci kamieniem",
    "Piwne przywileje",
    "Zawsze wybieram piwo",
    "Piwo na dźwięk otwieranej puszki",
    "Rozkoszuj się każdym łykiem",
    "Piwo, bo życie to nie tylko obowiązki",
    "Na świecie jest tyle piw, ile dni w roku",
    "Piwne inspiracje",
    "Kufel w ręku, a reszta się nie liczy",
    "Piwo - najlepszy sposób na zakończenie dnia",
    "Wypijmy za wszystkie piwne chwile",
    "Piwo to nie tylko napój, to tradycja",
    "Zawsze lepsze z kuflem w ręce",
    "Piwo, bo czemu nie?",
    "Kufel, przyjaciele i dobra zabawa",
    "Piwo, bo życie jest zbyt krótkie na kiepskie trunki",
    "Kufel zawsze w ruchu",
    "Piwo - smak wolności"
]



async def beer(message):
    if not message.author == client.user:
       if not isinstance(message.channel, discord.DMChannel):
          sign = message.content.lower() 
          if any(beer in sign for beer in beer_trigger):
             response = random.choice(beer_response)
             
             await message.channel.send(response)